[package]
name = "tokio"
version.workspace = true
edition.workspace = true
publish = false
default-run = "tokio"

[dependencies]
tokio = { version = "1.45", features = ["full"] }
derive-io = { workspace = true, features = ["tokio"] }
derive-io-macros = { workspace = true }

[[bin]]
name = "tokio"
